---

_userroles_indices_finder_prefix: "settings_userroles_"
_userroles_indices_finder_suffix: "_name"
_index_items_regex_pattern: "{{ common_index_items_regex_pattern | format( _userroles_indices_finder_prefix, _userroles_indices_finder_suffix) }}"

vars_userroles_enabled: "{{ lookup('env', '%sconfigure' | format(_userroles_indices_finder_prefix)) | default('false',true) }}"
vars_userroles_ignore_errors: "{{ lookup('env', '%sconfigure_ignore_errors' | format(_userroles_indices_finder_prefix)) | default(vars_default_ignore_errors,true) }}"

_userroles_template:
  lookup_id:
    name: "{{ lookup('env', '%s%s%s' | format(_userroles_indices_finder_prefix,index_item,_usergroups_indices_finder_suffix)) | default('',true) }}"
  data:
    name: "{{ lookup('env', '%s%s%s' | format(_userroles_indices_finder_prefix,index_item,_usergroups_indices_finder_suffix)) | default('',true) }}"
    description: "{{ lookup('env', '%s%s_description' | format(_userroles_indices_finder_prefix,index_item)) | default('',true) }}"
    summary: "{{ lookup('env', '%s%s_summary' | format(_userroles_indices_finder_prefix,index_item)) | default('',true) }}"