{{ if .Values.envSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "webmethods-devportal-configurator.fullname" . }}
  labels:
  {{- include "webmethods-devportal-configurator.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.envSecrets }}
    {{ $name }}: "{{ tpl $value $ | b64enc }}"
  {{- end }}
{{- end }}
