---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml

################################################################
## set configs via REST APIs
################################################################

- name: Reset passwords tasks
  hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  run_once: true
  tasks:

    - name: Self Reset Main REST API User password
      include_role:
        name: developerportal-rest-configurator
        apply:
          ignore_errors: yes
      vars:
        configs_action: users/self-update-password
        configs_enabled: "true"
        rvar_devportal_rest_auth_username: "{{ vars_rest_login_username }}"
        rvar_devportal_rest_auth_password: "{{ vars_rest_login_password_old }}"
        rvar_devportal_rest_users_selfupdatepassword: 
          oldPassword: "{{ vars_rest_login_password_old }}"
          newPassword: "{{ vars_rest_login_password }}"
