version: "3.2"

networks:
  stack:

services:

  devportal:
    image: ${REG_DEVPORTAL}${IMAGE_DEVPORTAL}:${TAG_DEVPORTAL}
    ports:
      - "8083:8083"
    environment: 
      SPRING_ELASTICSEARCH_REST_URIS: "http://elasticsearch:9200"
    networks:
      - stack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$TAG_ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.port=9200
      - transport.port=9300
    networks:
      - stack

  config_changepassword:
    image: ${REG_DEVPORTAL_CONFIGURATOR}webmethods-devportal-configurator:${TAG_DEVPORTAL_CONFIGURATOR}
    volumes:
      - ../resources/ansible/sagdevops-ansible-common:/ansible/roles/sagdevops-ansible-common-1.0.0-4:ro
      - ../resources/ansible/sagdevops-ansible-developer-portal:/ansible/roles/sagdevops-ansible-developer-portal-1.0.0-1:ro 
    environment: 
      connect_host: devportal
      connect_port: "8083"
      connect_user: Administrator
      connect_password: "somethingnew"
      changepassword_enabled: "true"
      changepassword_old: "manage"
    networks:
      - stack

  config_users:
    image: ${REG_DEVPORTAL_CONFIGURATOR}webmethods-devportal-configurator:${TAG_DEVPORTAL_CONFIGURATOR}
    volumes:
      - ../resources/ansible/sagdevops-ansible-common:/ansible/roles/sagdevops-ansible-common-1.0.0-4:ro
      - ../resources/ansible/sagdevops-ansible-developer-portal:/ansible/roles/sagdevops-ansible-developer-portal-1.0.0-1:ro 
    environment: 
      connect_host: devportal
      connect_port: "8083"
      connect_user: Administrator
      connect_password: "somethingnew"
      settings_users_configure: "true"
      settings_users_configure_ignore_errors: "false"
      settings_users_0_username: user1
      settings_users_0_password: password1
      settings_users_0_firstname: firstname1
      settings_users_0_lastname: lastname1
      settings_users_0_locale: "en_US"
      settings_users_1_username: user2
      settings_users_1_password: password2
      settings_users_1_firstname: firstname2
      settings_users_1_lastname: lastname2
      settings_users_1_locale: "en_US"
      settings_users_2_username: user3
      settings_users_2_password: password3
      settings_users_2_firstname: firstname3
      settings_users_2_lastname: lastname3
      settings_users_2_locale: "en_US"
    networks:
      - stack
