version: "3.2"

networks:
  stack:

services:

  devportal:
    image: ${REG_DEVPORTAL}${IMAGE_DEVPORTAL}:${TAG_DEVPORTAL}
    ports:
      - "8083:8083"
    environment: 
      SPRING_ELASTICSEARCH_REST_URIS: "http://elasticsearch:9200"
    networks:
      - stack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$TAG_ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.port=9200
      - transport.port=9300
    networks:
      - stack

  config_changepassword:
    image: ${REG_DEVPORTAL_CONFIGURATOR}webmethods-devportal-configurator:${TAG_DEVPORTAL_CONFIGURATOR}
    volumes:
      - ../resources/ansible/sagdevops-ansible-common:/ansible/roles/sagdevops-ansible-common-1.0.0-4:ro
      - ../resources/ansible/sagdevops-ansible-developer-portal:/ansible/roles/sagdevops-ansible-developer-portal-1.0.0-1:ro 
    environment: 
      devportal_connect_host: devportal
      devportal_connect_port: "8083"
      devportal_connect_user: Administrator
      devportal_connect_password: "somethingnew"
      devportal_changepassword_enabled: "true"
      devportal_changepassword_old: "manage"
    networks:
      - stack